### ISSUE TITLE
Release tracking for V0.2.0 - Polkadot m1, Queries, extras

### ISSUE THREAD

**Issue by flipchan** [XcmSend/app#32]
Prev:
https://github.com/XcmSend/app/issues/19

### Features:     
Threadbag  -   Continuously run your scenarios 
API 
Latest polkadot.js dependencies
Queries, instead of the 6 pallets we promised, we support queriing all pallets and storage entries on both relay and parachains.    
New XCM transfers 
Templates  

### Supported XCM transfers:   
 [ ] -  a

- [x]  Rococo <> Rococo Assethub
- [ ] Paseo(new test ) <> Paseo Assethub   
- [x]  Polkadot Assethub <> Kusama Assethub
- [ x] Kusama <> Kusama Assethub
- [x] Turing <> Moonriver
- [ ]  Turing > MangataX
- [ ] Kusama <> Turing 
- [ ]  Polkadot <> Interlay
- [x]  Polkadot <> Assethub  
- [x] Polkaodt <> HydraDX 
- [x]  HydraDx <> Polkadot Assethub
- [ ] 
Link to docs for each transfer

### Remarks
- [x] System remarks  
Examples docs link 

System remarks in api: https://github.com/XcmSend/api/pull/36 
```shell
$ curl -X POST -H "Content-Type: application/json" -d '{"chain": "polkadot", "msg": "hack the planet"}' http://localhost:8080/system-remark 
{"result":"0x4c0400073c6861636b2074686520706c616e6574"}
```

### Swaps:  
HydraDX powered swaps, support the following pools:

**Comment by flipchan** [comment]
https://github.com/XcmSend/docusaurus/issues/14

**Comment by flipchan** [comment]
:boom: :boom: release contains breaking api changes :boom: :boom: :boom:
